In [1]:
import pandas as pd
import numpy as np

In [3]:
subs = pd.read_csv("/content/subs (1).csv")

In [4]:
print(subs)

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [15]:
subs.value_counts()

Subscribers gained
105                   9
108                   6
88                    5
72                    5
123                   5
                     ..
295                   1
301                   1
306                   1
312                   1
396                   1
Name: count, Length: 180, dtype: int64

In [17]:
subs.sample()

     Subscribers gained
211                  98

In [18]:
subs.head(5)

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [19]:
subs.tail(5)

     Subscribers gained
360                 231
361                 226
362                 155
363                 144
364                 172

series math method

In [20]:
subs.count()

Subscribers gained    365
dtype: int64

In [21]:
subs.sum()

Subscribers gained    49510
dtype: int64

In [22]:
subs.prod()

Subscribers gained    0
dtype: int64

In [23]:
subs.mean()

Subscribers gained    135.643836
dtype: float64

In [25]:
subs.median()

Subscribers gained    123.0
dtype: float64

In [26]:
subs.std()

Subscribers gained    62.675023
dtype: float64

In [27]:
subs.var()

Subscribers gained    3928.158513
dtype: float64

In [28]:
subs.iloc[-1]

Subscribers gained    172
Name: 364, dtype: int64

In [31]:
subs.loc[7:9]  # mainly use for indexing

   Subscribers gained
7                  40
8                  44
9                  74

In [32]:
subs[-5:]

     Subscribers gained
360                 231
361                 226
362                 155
363                 144
364                 172

In [33]:
subs[::2]  # same as a for range function

     Subscribers gained
0                    48
2                    40
4                    44
6                    33
8                    44
..                  ...
356                 156
358                 210
360                 231
362                 155
364                 172

[183 rows x 1 columns]

In [38]:
subs.loc[[1,3,2,7]]

   Subscribers gained
1                  57
3                  43
2                  40
7                  40

Editing series

In [43]:
subs[1]=100
subs

     Subscribers gained    1
0                    48  100
1                    57  100
2                    40  100
3                    43  100
4                    44  100
..                  ...  ...
360                 231  100
361                 226  100
362                 155  100
363                 144  100
364                 172  100

[365 rows x 2 columns]

In [45]:
subs['evs']=100
subs

     Subscribers gained    1  evs
0                    48  100  100
1                    57  100  100
2                    40  100  100
3                    43  100  100
4                    44  100  100
..                  ...  ...  ...
360                 231  100  100
361                 226  100  100
362                 155  100  100
363                 144  100  100
364                 172  100  100

[365 rows x 3 columns]

In [47]:
subs[0]=1
subs

     Subscribers gained    1  evs  0
0                    48  100  100  1
1                    57  100  100  1
2                    40  100  100  1
3                    43  100  100  1
4                    44  100  100  1
..                  ...  ...  ... ..
360                 231  100  100  1
361                 226  100  100  1
362                 155  100  100  1
363                 144  100  100  1
364                 172  100  100  1

[365 rows x 4 columns]

In [56]:
subs[0:1]=[10,10]
subs

ValueError: Must have equal len keys and value when setting with an iterable

problem